namespace:
  name: sandbox
 
image:
  repository: boramgwon/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 4111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz


